// Code generated by generate.go; DO NOT EDIT.
// This file was automatically generated by generate.go
// Manual edits will be overwritten on next generation.

package msg

// Pre-serialized JSON representation of "Expiration" error.
// Contains byte array representing JSON structure:
// {
//   "error": {
//     "key": "EXPIRATION",
//     "message": "Token expiration"
//   }
// }
var errorExpirationJson = []byte{123, 34, 101, 114, 114, 111, 114, 34, 58, 123, 34, 107, 101, 121, 34, 58, 34, 69, 88, 80, 73, 82, 65, 84, 73, 79, 78, 34, 44, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 34, 84, 111, 107, 101, 110, 32, 101, 120, 112, 105, 114, 97, 116, 105, 111, 110, 34, 125, 125}

// Pre-serialized MessagePack representation of "Expiration" error.
// Binary-optimized format containing the same data as JSON version.
var errorExpirationMsgpack = []byte{129, 165, 101, 114, 114, 111, 114, 130, 163, 75, 101, 121, 170, 69, 88, 80, 73, 82, 65, 84, 73, 79, 78, 167, 77, 101, 115, 115, 97, 103, 101, 176, 84, 111, 107, 101, 110, 32, 101, 120, 112, 105, 114, 97, 116, 105, 111, 110}

// Expiration sends a pre-serialized error message to the client.
//
// Parameters:
//   - ctx: Request context (compatible with Fiber, Echo, Gin or other frameworks)
//   - format: Optional format parameter ("json" or "msgpack"). Defaults to JSON.
//
// Returns:
//   - error: Returns an error if there were problems sending the message
//
// Behavior:
// - Automatically sets appropriate Content-Type header
// - Supports multiple frameworks through unified interface
// - Uses pre-serialized data for maximum performance
// - Defaults to JSON format if none specified
func Expiration(ctx any, format ...string) error {
    return send(ctx, errorExpirationJson, errorExpirationMsgpack, format...)
}
