// Code generated by generate.go; DO NOT EDIT.
// This file was automatically generated by generate.go
// Manual edits will be overwritten on next generation.

package msg

// Pre-serialized JSON representation of "Forbidden" error.
// Contains byte array representing JSON structure:
// {
//   "error": {
//     "key": "FORBIDDEN",
//     "message": "Forbidden"
//   }
// }
var errorForbiddenJson = []byte{123, 34, 101, 114, 114, 111, 114, 34, 58, 123, 34, 107, 101, 121, 34, 58, 34, 70, 79, 82, 66, 73, 68, 68, 69, 78, 34, 44, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 34, 70, 111, 114, 98, 105, 100, 100, 101, 110, 34, 125, 125}

// Pre-serialized MessagePack representation of "Forbidden" error.
// Binary-optimized format containing the same data as JSON version.
var errorForbiddenMsgpack = []byte{129, 165, 101, 114, 114, 111, 114, 130, 163, 75, 101, 121, 169, 70, 79, 82, 66, 73, 68, 68, 69, 78, 167, 77, 101, 115, 115, 97, 103, 101, 169, 70, 111, 114, 98, 105, 100, 100, 101, 110}

// Forbidden sends a pre-serialized error message to the client.
//
// Parameters:
//   - ctx: Request context (compatible with Fiber, Echo, Gin or other frameworks)
//   - format: Optional format parameter ("json" or "msgpack"). Defaults to JSON.
//
// Returns:
//   - error: Returns an error if there were problems sending the message
//
// Behavior:
// - Automatically sets appropriate Content-Type header
// - Supports multiple frameworks through unified interface
// - Uses pre-serialized data for maximum performance
// - Defaults to JSON format if none specified
func Forbidden(ctx any, format ...string) error {
    return send(ctx, errorForbiddenJson, errorForbiddenMsgpack, format...)
}
