// Code generated by generate.go; DO NOT EDIT.
// This file was automatically generated by generate.go
// Manual edits will be overwritten on next generation.

package msg

// Pre-serialized JSON representation of "InternalError" error.
// Contains byte array representing JSON structure:
// {
//   "error": {
//     "key": "INTERNAL_ERROR",
//     "message": "An unexpected internal server error occurred"
//   }
// }
var errorInternalErrorJson = []byte{123, 34, 101, 114, 114, 111, 114, 34, 58, 123, 34, 107, 101, 121, 34, 58, 34, 73, 78, 84, 69, 82, 78, 65, 76, 95, 69, 82, 82, 79, 82, 34, 44, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 34, 65, 110, 32, 117, 110, 101, 120, 112, 101, 99, 116, 101, 100, 32, 105, 110, 116, 101, 114, 110, 97, 108, 32, 115, 101, 114, 118, 101, 114, 32, 101, 114, 114, 111, 114, 32, 111, 99, 99, 117, 114, 114, 101, 100, 34, 125, 125}

// Pre-serialized MessagePack representation of "InternalError" error.
// Binary-optimized format containing the same data as JSON version.
var errorInternalErrorMsgpack = []byte{129, 165, 101, 114, 114, 111, 114, 130, 163, 75, 101, 121, 174, 73, 78, 84, 69, 82, 78, 65, 76, 95, 69, 82, 82, 79, 82, 167, 77, 101, 115, 115, 97, 103, 101, 217, 44, 65, 110, 32, 117, 110, 101, 120, 112, 101, 99, 116, 101, 100, 32, 105, 110, 116, 101, 114, 110, 97, 108, 32, 115, 101, 114, 118, 101, 114, 32, 101, 114, 114, 111, 114, 32, 111, 99, 99, 117, 114, 114, 101, 100}

// InternalError sends a pre-serialized error message to the client.
//
// Parameters:
//   - ctx: Request context (compatible with Fiber, Echo, Gin or other frameworks)
//   - format: Optional format parameter ("json" or "msgpack"). Defaults to JSON.
//
// Returns:
//   - error: Returns an error if there were problems sending the message
//
// Behavior:
// - Automatically sets appropriate Content-Type header
// - Supports multiple frameworks through unified interface
// - Uses pre-serialized data for maximum performance
// - Defaults to JSON format if none specified
func InternalError(ctx any, format ...string) error {
    return send(ctx, errorInternalErrorJson, errorInternalErrorMsgpack, format...)
}
