// Code generated by generate.go; DO NOT EDIT.
// This file was automatically generated by generate.go
// Manual edits will be overwritten on next generation.

package msg

// Pre-serialized JSON representation of "ManyRequest" error.
// Contains byte array representing JSON structure:
// {
//   "error": {
//     "key": "MANY_REQUEST",
//     "message": "To many request"
//   }
// }
var errorManyRequestJson = []byte{123, 34, 101, 114, 114, 111, 114, 34, 58, 123, 34, 107, 101, 121, 34, 58, 34, 77, 65, 78, 89, 95, 82, 69, 81, 85, 69, 83, 84, 34, 44, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 34, 84, 111, 32, 109, 97, 110, 121, 32, 114, 101, 113, 117, 101, 115, 116, 34, 125, 125}

// Pre-serialized MessagePack representation of "ManyRequest" error.
// Binary-optimized format containing the same data as JSON version.
var errorManyRequestMsgpack = []byte{129, 165, 101, 114, 114, 111, 114, 130, 163, 75, 101, 121, 172, 77, 65, 78, 89, 95, 82, 69, 81, 85, 69, 83, 84, 167, 77, 101, 115, 115, 97, 103, 101, 175, 84, 111, 32, 109, 97, 110, 121, 32, 114, 101, 113, 117, 101, 115, 116}

// ManyRequest sends a pre-serialized error message to the client.
//
// Parameters:
//   - ctx: Request context (compatible with Fiber, Echo, Gin or other frameworks)
//   - format: Optional format parameter ("json" or "msgpack"). Defaults to JSON.
//
// Returns:
//   - error: Returns an error if there were problems sending the message
//
// Behavior:
// - Automatically sets appropriate Content-Type header
// - Supports multiple frameworks through unified interface
// - Uses pre-serialized data for maximum performance
// - Defaults to JSON format if none specified
func ManyRequest(ctx any, format ...string) error {
    return send(ctx, errorManyRequestJson, errorManyRequestMsgpack, format...)
}
