// Code generated by generate.go; DO NOT EDIT.
// This file was automatically generated by generate.go
// Manual edits will be overwritten on next generation.

package msg

// Pre-serialized JSON representation of "NotFound" error.
// Contains byte array representing JSON structure:
// {
//   "error": {
//     "key": "NOT_FOUND",
//     "message": "The requested resource could not be found"
//   }
// }
var errorNotFoundJson = []byte{123, 34, 101, 114, 114, 111, 114, 34, 58, 123, 34, 107, 101, 121, 34, 58, 34, 78, 79, 84, 95, 70, 79, 85, 78, 68, 34, 44, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 34, 84, 104, 101, 32, 114, 101, 113, 117, 101, 115, 116, 101, 100, 32, 114, 101, 115, 111, 117, 114, 99, 101, 32, 99, 111, 117, 108, 100, 32, 110, 111, 116, 32, 98, 101, 32, 102, 111, 117, 110, 100, 34, 125, 125}

// Pre-serialized MessagePack representation of "NotFound" error.
// Binary-optimized format containing the same data as JSON version.
var errorNotFoundMsgpack = []byte{129, 165, 101, 114, 114, 111, 114, 130, 163, 75, 101, 121, 169, 78, 79, 84, 95, 70, 79, 85, 78, 68, 167, 77, 101, 115, 115, 97, 103, 101, 217, 41, 84, 104, 101, 32, 114, 101, 113, 117, 101, 115, 116, 101, 100, 32, 114, 101, 115, 111, 117, 114, 99, 101, 32, 99, 111, 117, 108, 100, 32, 110, 111, 116, 32, 98, 101, 32, 102, 111, 117, 110, 100}

// NotFound sends a pre-serialized error message to the client.
//
// Parameters:
//   - ctx: Request context (compatible with Fiber, Echo, Gin or other frameworks)
//   - format: Optional format parameter ("json" or "msgpack"). Defaults to JSON.
//
// Returns:
//   - error: Returns an error if there were problems sending the message
//
// Behavior:
// - Automatically sets appropriate Content-Type header
// - Supports multiple frameworks through unified interface
// - Uses pre-serialized data for maximum performance
// - Defaults to JSON format if none specified
func NotFound(ctx any, format ...string) error {
    return send(ctx, errorNotFoundJson, errorNotFoundMsgpack, format...)
}
