// Code generated by generate.go; DO NOT EDIT.
// This file was automatically generated by generate.go
// Manual edits will be overwritten on next generation.

package msg

// Pre-serialized JSON representation of "OutdatedVersion" error.
// Contains byte array representing JSON structure:
// {
//   "error": {
//     "key": "OUTDATED_VERSION",
//     "message": "Outdated version of the application"
//   }
// }
var errorOutdatedVersionJson = []byte{123, 34, 101, 114, 114, 111, 114, 34, 58, 123, 34, 107, 101, 121, 34, 58, 34, 79, 85, 84, 68, 65, 84, 69, 68, 95, 86, 69, 82, 83, 73, 79, 78, 34, 44, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 34, 79, 117, 116, 100, 97, 116, 101, 100, 32, 118, 101, 114, 115, 105, 111, 110, 32, 111, 102, 32, 116, 104, 101, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 34, 125, 125}

// Pre-serialized MessagePack representation of "OutdatedVersion" error.
// Binary-optimized format containing the same data as JSON version.
var errorOutdatedVersionMsgpack = []byte{129, 165, 101, 114, 114, 111, 114, 130, 163, 75, 101, 121, 176, 79, 85, 84, 68, 65, 84, 69, 68, 95, 86, 69, 82, 83, 73, 79, 78, 167, 77, 101, 115, 115, 97, 103, 101, 217, 35, 79, 117, 116, 100, 97, 116, 101, 100, 32, 118, 101, 114, 115, 105, 111, 110, 32, 111, 102, 32, 116, 104, 101, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110}

// OutdatedVersion sends a pre-serialized error message to the client.
//
// Parameters:
//   - ctx: Request context (compatible with Fiber, Echo, Gin or other frameworks)
//   - format: Optional format parameter ("json" or "msgpack"). Defaults to JSON.
//
// Returns:
//   - error: Returns an error if there were problems sending the message
//
// Behavior:
// - Automatically sets appropriate Content-Type header
// - Supports multiple frameworks through unified interface
// - Uses pre-serialized data for maximum performance
// - Defaults to JSON format if none specified
func OutdatedVersion(ctx any, format ...string) error {
    return send(ctx, errorOutdatedVersionJson, errorOutdatedVersionMsgpack, format...)
}
