// Code generated by generate.go; DO NOT EDIT.
// This file was automatically generated by generate.go
// Manual edits will be overwritten on next generation.

package msg

// Pre-serialized JSON representation of "UnknownError" error.
// Contains byte array representing JSON structure:
// {
//   "error": {
//     "key": "UNKNOWN_ERROR",
//     "message": "An unknown error has occurred. Please try again later."
//   }
// }
var errorUnknownErrorJson = []byte{123, 34, 101, 114, 114, 111, 114, 34, 58, 123, 34, 107, 101, 121, 34, 58, 34, 85, 78, 75, 78, 79, 87, 78, 95, 69, 82, 82, 79, 82, 34, 44, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 34, 65, 110, 32, 117, 110, 107, 110, 111, 119, 110, 32, 101, 114, 114, 111, 114, 32, 104, 97, 115, 32, 111, 99, 99, 117, 114, 114, 101, 100, 46, 32, 80, 108, 101, 97, 115, 101, 32, 116, 114, 121, 32, 97, 103, 97, 105, 110, 32, 108, 97, 116, 101, 114, 46, 34, 125, 125}

// Pre-serialized MessagePack representation of "UnknownError" error.
// Binary-optimized format containing the same data as JSON version.
var errorUnknownErrorMsgpack = []byte{129, 165, 101, 114, 114, 111, 114, 130, 163, 75, 101, 121, 173, 85, 78, 75, 78, 79, 87, 78, 95, 69, 82, 82, 79, 82, 167, 77, 101, 115, 115, 97, 103, 101, 217, 54, 65, 110, 32, 117, 110, 107, 110, 111, 119, 110, 32, 101, 114, 114, 111, 114, 32, 104, 97, 115, 32, 111, 99, 99, 117, 114, 114, 101, 100, 46, 32, 80, 108, 101, 97, 115, 101, 32, 116, 114, 121, 32, 97, 103, 97, 105, 110, 32, 108, 97, 116, 101, 114, 46}

// UnknownError sends a pre-serialized error message to the client.
//
// Parameters:
//   - ctx: Request context (compatible with Fiber, Echo, Gin or other frameworks)
//   - format: Optional format parameter ("json" or "msgpack"). Defaults to JSON.
//
// Returns:
//   - error: Returns an error if there were problems sending the message
//
// Behavior:
// - Automatically sets appropriate Content-Type header
// - Supports multiple frameworks through unified interface
// - Uses pre-serialized data for maximum performance
// - Defaults to JSON format if none specified
func UnknownError(ctx any, format ...string) error {
    return send(ctx, errorUnknownErrorJson, errorUnknownErrorMsgpack, format...)
}
